Added the tabindex property to IconButton
Gemeente-DenHaag/denhaag-component-library pull request #191
Opened 2021-05-25 08:40 UTC by DanielvanVliet

This might not be something we want to expose like this, but tabIndex is necessary for the design implementation for list.

2021-05-25 09:24 UTC, bddjong approved these changes

2021-05-25 09:24 UTC, bddjong commented on src/components/IconButton/src/index.tsx
> +  tabIndex?: number;
I'm fine with exposing this property. Users should be able to decide for themselves how to use a component under their own circumstances.

2021-05-25 17:13 UTC, GewoonMaarten submitted a review, later dismissed

2021-05-26 07:07 UTC, bddjong commented on src/components/IconButton/src/index.tsx
> +  tabIndex?: number;
Move this to baseprops

2021-05-26 08:03 UTC, bddjong requested changes
Submit rereview when tabindex has been moved to baseprops

2021-05-26 09:15 UTC, joostvanviegen approved these changes

2021-05-26 09:16 UTC, GewoonMaarten approved these changes

2021-05-26 09:39 UTC, merged